name: CUDA Build

on:
  push:
    branches:
      - V2.0  # Change to your default branch name
  pull_request:
    branches:
      - V2.0  # Change to your default branch name
  release:
    types: [created]  # Trigger on release creation

jobs:
  build-windows:
    runs-on: windows-2022  # Use the latest Windows image with pre-installed tools

    steps:
    - name: Check out code
      uses: actions/checkout@v3  # Use the latest version of checkout action

    - name: Set up CUDA Environment
      run: |
        # Set CUDA path
        $env:CUDA_PATH = "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6"
        $env:Path += ";$env:CUDA_PATH\bin;$env:CUDA_PATH\libnvvp"
        
        # Print important environment variables
        Write-Host "CUDA_PATH: $env:CUDA_PATH"
        Write-Host "PATH: $env:Path"

    - name: List CUDA bin directory
      run: |
        # List the contents of the CUDA bin directory to verify nvcc installation
        Get-ChildItem "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\bin"

    - name: Verify CUDA Installation
      run: |
        # Verify CUDA installation
        nvcc --version

    - name: Build with MSBuild
      run: |
        # Build the solution using the installed MSBuild
        & "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe" BruteForceMnemonicCUDA.sln /p:Configuration=Release

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1  # Use the latest version of the release action
      with:
        tag: ${{ github.ref }}
        files: x64/Release/BruteForceMnemonicBitcoinV200.exe  # Specify the correct path to your executable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
